// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Belt_List = require("bs-platform/lib/js/belt_List.js");

function getBox(startCoord, endCoord) {
  if (startCoord && endCoord) {
    return /* Some */[/* tuple */[
              startCoord[0],
              endCoord[0]
            ]];
  } else {
    return /* None */0;
  }
}

function addToList(startCoord, endCoord, boxes) {
  var match = getBox(startCoord, endCoord);
  if (match) {
    return Belt_List.add(boxes, match[0]);
  } else {
    return boxes;
  }
}

function boxMiddleware(reducer) {
  var state = reducer[1];
  switch (reducer[0].tag | 0) {
    case 0 : 
    case 1 : 
        return state;
    case 2 : 
        return /* record */[
                /* startCoord */state[/* startCoord */0],
                /* endCoord */state[/* endCoord */1],
                /* boxes */addToList(state[/* startCoord */0], state[/* endCoord */1], state[/* boxes */2])
              ];
    
  }
}

exports.getBox = getBox;
exports.addToList = addToList;
exports.boxMiddleware = boxMiddleware;
/* No side effect */
