// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';


function canvasMiddleware(reducer) {
  var action = reducer[0];
  var newState;
  var exit = 0;
  switch (action.tag | 0) {
    case 0 : 
        newState = /* record */[
          /* startCoord : Some */[/* record */[
              /* x */action[0],
              /* y */action[1]
            ]],
          /* endCoord : None */0
        ];
        break;
    case 1 : 
    case 2 : 
        exit = 1;
        break;
    
  }
  if (exit === 1) {
    newState = /* record */[
      /* startCoord */reducer[1][/* startCoord */0],
      /* endCoord : Some */[/* record */[
          /* x */action[0],
          /* y */action[1]
        ]]
    ];
  }
  return /* tuple */[
          action,
          newState
        ];
}

exports.canvasMiddleware = canvasMiddleware;
/* No side effect */
