// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';


function canvasMiddleware(reducer) {
  var state = reducer[1];
  var action = reducer[0];
  var newState;
  switch (action.tag | 0) {
    case 0 : 
    case 1 : 
        newState = /* record */[
          /* count */state[/* count */0],
          /* show */1 - state[/* show */1]
        ];
        break;
    case 2 : 
        newState = /* record */[
          /* count */state[/* count */0] + 1 | 0,
          /* show */state[/* show */1]
        ];
        break;
    
  }
  return /* tuple */[
          action,
          newState
        ];
}

exports.canvasMiddleware = canvasMiddleware;
/* No side effect */
