// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';


function logMiddleware(reducer) {
  var state = reducer[1];
  console.log("LOG", state);
  return state;
}

exports.logMiddleware = logMiddleware;
/* No side effect */
