// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Curry = require("bs-platform/lib/js/curry.js");

function runMiddlewares(reducer, middlewares) {
  return List.fold_right((function (middleware, data) {
                var newState = Curry._1(middleware, data);
                return /* tuple */[
                        data[0],
                        newState
                      ];
              }), middlewares, reducer);
}

function pipeMiddlewares(reducer, middlewares) {
  return runMiddlewares(reducer, middlewares)[1];
}

exports.runMiddlewares = runMiddlewares;
exports.pipeMiddlewares = pipeMiddlewares;
/* No side effect */
