// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Reducer$ReactTemplate = require("./Reducer.bs.js");
var LogMiddleware$ReactTemplate = require("./middlewares/logMiddleware.bs.js");
var CanvasMiddleware$ReactTemplate = require("./middlewares/canvasMiddleware.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, Reducer$ReactTemplate.make(/* :: */[
              LogMiddleware$ReactTemplate.logMiddleware,
              /* :: */[
                CanvasMiddleware$ReactTemplate.canvasMiddleware,
                /* [] */0
              ]
            ], /* array */[])), "index2");

/*  Not a pure module */
