// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var Canvas$ReactTemplate = require("./Canvas.bs.js");
var PipeMiddlewares$ReactTemplate = require("./utils/PipeMiddlewares.bs.js");

var component = ReasonReact.reducerComponent("ReducerComponent");

function make(middlewares, initial, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (self) {
      var reducerInterface_000 = /* state */self[/* state */2];
      var reducerInterface_001 = /* send */self[/* send */4];
      var reducerInterface = /* record */[
        reducerInterface_000,
        reducerInterface_001
      ];
      return ReasonReact.element(/* None */0, /* None */0, Canvas$ReactTemplate.make(reducerInterface, /* array */[]));
    });
  newrecord[/* initialState */10] = (function () {
      return initial;
    });
  newrecord[/* reducer */12] = (function (param, param$1) {
      return PipeMiddlewares$ReactTemplate.doReducer(middlewares, param, param$1);
    });
  return newrecord;
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
