// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Canvas$ReactTemplate = require("./Canvas.bs.js");
var PipeMiddlewares$ReactTemplate = require("./utils/PipeMiddlewares.bs.js");

var component = ReasonReact.reducerComponent("ReducerComponent");

function make(middlewares, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (self) {
      var reducerInterface_000 = /* state */self[/* state */2];
      var reducerInterface_001 = /* send */self[/* send */4];
      var reducerInterface = /* record */[
        reducerInterface_000,
        reducerInterface_001
      ];
      return ReasonReact.element(/* None */0, /* None */0, Canvas$ReactTemplate.make(reducerInterface, /* array */[]));
    });
  newrecord[/* initialState */10] = (function () {
      return /* record */[
              /* count */0,
              /* show : true */1
            ];
    });
  newrecord[/* reducer */12] = (function (action, state) {
      return /* Update */Block.__(0, [PipeMiddlewares$ReactTemplate.pipeMiddlewares(/* tuple */[
                      action,
                      state
                    ], middlewares)]);
    });
  return newrecord;
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
